/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package main;

import controller.ProjectController;
import java.util.List;
import model.Project;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
       
        ProjectController projetoController = new ProjectController();
        
        Project p1 = new Project();
        
        List<Project> listarProjetos = projetoController.getAll();
       
        System.out.println("Teste" + listarProjetos.toString() );
        
        
        
    }
}
